---
title: "Analysis"
execute:
  warning: false
  message: false
---

```{r}
#| label: timestamp-start
#| echo: false

timestamp()
```

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

```{r}
#| label: load-data
#| include: false

load(here("data", "data_constructed", "exogamy_trends.RData"))
load(here("data", "data_constructed", "model_state_bs.RData"))
load(here("data", "data_constructed", "model_basic_bs.RData"))
load(here("data", "data_constructed", "models_subgroups.RData"))
load(here("data", "data_constructed", "models_counterfactual.RData"))
load(here("data", "data_constructed", "model_region.RData"))
load(here("data", "data_constructed", "models_state_gen_bs.RData"))
load(here("data", "data_constructed", "model_recent_mar.RData"))
load(here("data", "data_constructed", "model_same_sex.RData"))
```

```{r}
#| label: set-color-palette

palette <- c(
  # Single race combinations
  "White/Black"                   = "#E69F00",  # rich orange
  "White/AIAN"                    = "#009E73",  # teal green
  "White/API"                     = "#CC79A7",  # muted magenta
  "White/Hispanic"                = "#661100",  # deep rust
  "Black/AIAN"                    = "#A65628",  # warm brown
  "Black/API"                     = "#74AA99",  # muted cyan
  "Black/Hispanic"                = "#882255",  # deep burgundy
  "AIAN/API"                      = "#56B4E9",  # desaturated turquoise
  "AIAN/Hispanic"                 = "#AA4499",  # dusty rose
  "API/Hispanic"                  = "#117733",  # forest green
  
  # Single race to multiracial combinations
  "White/White-Black"             = "#47AC11",  # vivid spring green
  "Black/White-Black"             = "#471624",  # deep maroon-brown
  "White/White-AIAN"              = "#361892",  # royal indigo
  "AIAN/White-AIAN"               = "#23A4BB",  # bright teal-blue
  "White/White-API"               = "#667AA3",  # slate blue
  "API/White-API"                 = "#6D7003",  # olive drab
  "Black/Black-API"               = "#1117AA",  # bold cobalt blue
  "API/Black-API"                 = "#6D4113",  # dark umber
  "Black/Black-AIAN"              = "#7171BB",  # muted periwinkle
  "AIAN/Black-AIAN"               = "#422D13",  # earthy espresso

  # Hispanic subgroups with White and Black
  "White/WhiteHispanic"           = "#9E9E00",  # olive yellow
  "White/BlackHispanic"           = "#AA0055",  # rose plum
  "White/OtherHispanic"           = "#4FAA37",  # leafy green
  "Black/WhiteHispanic"           = "#552288",  # soft purple
  "Black/BlackHispanic"           = "#AA3344",  # reddish brick
  "Black/OtherHispanic"           = "#2C37DA",  # vivid sapphire

  # Asian subgroups with White
  "White/EastAsian"               = "#3366AA",  # steely blue
  "White/SEAsian"                 = "#118877",  # sea green
  "White/SouthAsian"              = "#9933AA",  # muted violet-magenta

  # Indigenous subgroups with White
  "White/AIAN"                    = "#CC4477",  # muted raspberry rose
  "White/PI"                      = "#3311EE",  # steel sky blue
  
  # Intra-Hispanic
  "WhiteHispanic/BlackHispanic"   = "#BB8866",  # muted tan
  "WhiteHispanic/OtherHispanic"   = "#885577",  # dusty mauve
  "BlackHispanic/OtherHispanic"   = "#AA8844",  # muted amber
  
  # Intra-Asian
  "EastAsian/SEAsian"             = "#336633",  # forest moss
  "EastAsian/SouthAsian"          = "#993399",  # grape violet
  "SEAsian/SouthAsian"            = "#CC6666",  # muted rose

  # Intra-Indigenous
  "AIAN/PI"                       = "#447777"   # muted teal gray
)

```

# Basic Trends in Outmarriage

```{r}
#| label: fig-outmarriage-overall
#| fig-cap: The trend in the probability that a marriage is racially exogamous. Values in all years are weighted to reflect the joint age distribution of newlywed partners. 95% confidence band shown.
  
ggplot(exogamy_trend, aes(x = year, y = exogamy, group = 1))+
  geom_ribbon(aes(ymin = exogamy-1.96*exogamy_se,
                  ymax = exogamy+1.96*exogamy_se),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point()+
  scale_y_continuous(labels = scales::percent)+
  labs(y = "percent of marriages that are racially exogamous")+
  theme_bw()
```

```{r}
#| label: fig-outmarriage-race
#| fig-cap: The trend in the probability that a spouse of a given race is racially exogamous, separately by gender. Values in all years are weighted to reflect the joint age distribution of newlywed partners. 95% confidence bands shown.

exogamy_trend_race |>
  filter(!str_detect(race, "-")) |>
  ggplot(aes(x = year, y = exogamy, color = spouse, group = spouse))+
  geom_ribbon(aes(ymin = exogamy-1.96*exogamy_se,
                  ymax = exogamy+1.96*exogamy_se, 
                  fill = spouse),
              alpha = 0.3, color = NA)+
  geom_line(alpha = 0.7)+
  geom_point(size = 1, alpha = 0.7)+
  facet_wrap(~race)+
  labs(y = "percent of spouses of given race that are racially exogamous")+
  scale_y_continuous(labels = scales::percent)+
  scale_color_manual(values = c("red", "navy", "gold"))+
  theme_bw()
```

# Overall Trends in Odds Ratios

```{r}
#| label: fig-intermar-single-overall
#| fig-cap: Odds of racial exogamy across all single race pairings, separately by the focal race of spouse
#| layout-ncol: 2
#| fig-subcap: 
#|    - White partner
#|    - Black partner
#|    - Indigenous partner
#|    - Asian partner
#|    - Hispanic partner

model_single_state_bs <- model_state_bs |>
  filter(!str_detect(term, "-"))

lims <- exp(c(min(model_single_state_bs$conf.low), 
              max(model_single_state_bs$conf.high)))

model_single_state_bs |>
  filter(str_detect(term, "White")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10(limits = lims)+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()

model_single_state_bs |>
  filter(str_detect(term, "Black")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10(limits = lims)+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()

model_single_state_bs |>
  filter(str_detect(term, "AIAN")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10(limits = lims)+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()

model_single_state_bs |>
  filter(str_detect(term, "API")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10(limits = lims)+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()

model_single_state_bs |>
  filter(str_detect(term, "Hispanic")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10(limits = lims)+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()
```

```{r}
#| label: fig-intermar-multi-overall
#| fig-cap: Odds of racial exogamy for biracial groups with component single race groups and in comparison to the odds of racial exogamy for the component single race groups
#| layout-ncol: 2
#| fig-subcap: 
#|    - White-Black
#|    - White-AIAN
#|    - White-API
#|    - Black-AIAN
#|    - Black-API

model_state_bs |>
  filter(term == "White/Black" | str_detect(term, "White-Black")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()

model_state_bs |>
  filter(term == "White/AIAN" | str_detect(term, "White-AIAN")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()

model_state_bs |>
  filter(term == "White/API" | str_detect(term, "White-API")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()

model_state_bs |>
  filter(term == "Black/AIAN" | str_detect(term, "Black-AIAN")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()

model_state_bs |>
  filter(term == "Black/API" | str_detect(term, "Black-API")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()
```


# Current Marriage Comparison

```{r}
#| label: fig-intermar-cur-mar
#| fig-cap: Odds of racial exogamy for single race groups, by age weighting and recent marriages

# add in missing values to break line
model_recent_mar <- expand_grid(term = unique(model_recent_mar$term), 
                                year = c(1990, 2000:2007),) |>
  bind_rows(model_recent_mar) |>
  mutate(identifier = "<= 1 year duration")

model_single_state_bs |>
  mutate(identifier = "age weighted") |>
  bind_rows(model_recent_mar) |>
  ggplot(aes(x = year, y = exp(estimate), group = identifier, color = identifier))+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = identifier),
              alpha = 0.3, color = NA)+
  geom_point(size = 1)+
  geom_line()+
  facet_wrap(~term)+
  scale_color_manual(values = c("red", "navy", "darkgreen"))+
  scale_fill_manual(values = c("red", "navy", "darkgreen"))+
  scale_y_log10()+
  theme_bw()



```

# Generation Comparison

```{r}
#| label: fig-intermar-single-gen
#| fig-cap: Odds of racial exogamy for single race groups, by different generational composition

model_state_single_all_gen_bs <- model_state_single_all_gen_bs |>
  mutate(gen = "all")

model_state_single_no_first_gen_bs <- model_state_single_no_first_gen_bs |>
  mutate(gen = "1.5 and 2nd+")

model_single_state_bs |>
  mutate(gen = "2nd+ only") |>
  bind_rows(model_state_single_all_gen_bs) |>
  bind_rows(model_state_single_no_first_gen_bs) |>
  ggplot(aes(x = year, y = exp(estimate), group = gen, color = gen))+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = gen),
              alpha = 0.3, color = NA)+
  geom_point(size = 1)+
  geom_line()+
  facet_wrap(~term, scales = "free_y")+
  scale_color_manual(values = c("red", "navy", "darkgreen"))+
  scale_fill_manual(values = c("red", "navy", "darkgreen"))+
  scale_y_log10()+
  theme_bw()
```

# Cohabitation Analysis

```{r}
#| label: load-cohab-models

load(here("data", "data_constructed", "models_cohab.RData"))
```


```{r}
#| label: fig-intermar-cohab
#| fig-cap: Odds of racial exogamy for single race groups by different union types

model_state_bs <- model_state_bs |>
  mutate(union_type = "marriage")

model_state_combine_bs <- model_state_combine_bs |>
  mutate(union_type = "both")

model_state_cohab_bs |>
  mutate(union_type = "cohabitation") |>
  bind_rows(model_state_combine_bs) |>
  bind_rows(model_state_bs) |>
  filter(!str_detect(term, "-")) |>
  mutate(union_type = factor(union_type, 
                             levels = c("marriage", "cohabitation", "both"))) |>
  ggplot(aes(x = year, y = exp(estimate), color = union_type))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = union_type),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  facet_wrap(~term)+
  scale_y_log10(limits = lims)+
  scale_color_manual(values = c("red", "navy", "darkgreen"))+
  scale_fill_manual(values = c("red", "navy", "darkgreen"))+
  theme_bw()
```

# Same Sex Analysis

```{r}
#| label: fig-intermar-same-sex
#| fig-cap: Odds of racial exogamy for single race groups by same and different sex

model_state_bs <- model_state_bs |>
  mutate(union_type = "opposite-sex")

model_state_same_sex_bs |>
  mutate(union_type = "same-sex") |>
  bind_rows(model_state_bs) |>
  filter(!str_detect(term, "-") &
           year >= 2010) |>
  mutate(union_type = factor(union_type)) |>
  ggplot(aes(x = year, y = exp(estimate), color = union_type))+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = union_type),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  facet_wrap(~term)+
  scale_y_log10()+
  scale_color_manual(values = c("red", "navy"))+
  scale_fill_manual(values = c("red", "navy"))+
  theme_bw()
```

```{r}
#| label: fig-intermar-same-sex2
#| fig-cap: Odds of racial exogamy for single race groups by same and different sex

load(here("data", "data_constructed", "models_cohab.RData"))

model_state_bs <- model_state_bs |>
  mutate(union_type = "opposite-sex marriage")

model_state_cohab_bs <- model_state_cohab_bs |>
  mutate(union_type = "opposite-sex cohabitation")

model_state_same_sex_bs |>
  mutate(union_type = "same-sex marriage") |>
  bind_rows(model_state_bs) |>
  bind_rows(model_state_cohab_bs) |>
  filter(!str_detect(term, "-") & str_detect(term, "White") &
           year >= 1990) |>
  mutate(union_type = factor(union_type,
                             levels = c("opposite-sex marriage",
                                        "opposite-sex cohabitation",
                                        "same-sex marriage"))) |>
  ggplot(aes(x = year, y = exp(estimate), color = union_type))+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = union_type),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  facet_wrap(~term)+
  scale_y_log10()+
  scale_color_manual(values = c("navy", "red", "darkgreen"))+
  scale_fill_manual(values = c("navy", "red", "darkgreen"))+
  theme_bw()
```


# Counterfactual Race Assignment

```{r}
#| label: fig-multi-wb-counterf
#| fig-cap: Comparison of White/Black exogamy when White-Black partners are re-assigned as Black or White

model_state_bs |>
  mutate(counterfactual = "Actual") |>
  bind_rows(model_cf_white_state_bs) |>
  bind_rows(model_cf_minority_state_bs) |>
  bind_rows(model_cf_best_state_bs) |>
  filter(term == "White/Black") |>
  mutate(counterfactual = if_else(counterfactual == "Minority", "Black",
                                  counterfactual),
         counterfactual = factor(counterfactual, 
                                 levels = c("Actual", "White", "Black", 
                                            "Best"))) |>
  ggplot(aes(x = year, y = exp(estimate), color = counterfactual))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), 
                  fill = counterfactual),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = c("red", "gold", "navy", "darkgreen"))+
  scale_fill_manual(values = c("red", "gold", "navy", "darkgreen"))+
  theme_bw()
```

```{r}
#| label: fig-multi-wa-counterf
#| fig-cap: Comparison of White/API exogamy when White-API partners are re-assigned as API or White

model_state_bs |>
  mutate(counterfactual = "Actual") |>
  bind_rows(model_cf_white_state_bs) |>
  bind_rows(model_cf_minority_state_bs) |>
  bind_rows(model_cf_best_state_bs) |>
  filter(term == "White/API") |>
  mutate(counterfactual = if_else(counterfactual == "Minority", "API",
                                  counterfactual),
         counterfactual = factor(counterfactual, 
                                 levels = c("Actual", "White", "API", 
                                            "Best"))) |>
  ggplot(aes(x = year, y = exp(estimate), color = counterfactual))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), 
                  fill = counterfactual),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = c("red", "gold", "navy", "darkgreen"))+
  scale_fill_manual(values = c("red", "gold", "navy", "darkgreen"))+
  theme_bw()
```

```{r}
#| label: fig-multi-wi-counterf
#| fig-cap: Comparison of White/AIAN exogamy when White-AIAN partners are re-assigned as AIAN or White

model_state_bs |>
  mutate(counterfactual = "Actual") |>
  bind_rows(model_cf_white_state_bs) |>
  bind_rows(model_cf_minority_state_bs) |>
  bind_rows(model_cf_best_state_bs) |>
  filter(term == "White/AIAN") |>
  mutate(counterfactual = if_else(counterfactual == "Minority", "AIAN",
                                  counterfactual),
         counterfactual = factor(counterfactual, 
                                 levels = c("Actual", "White", "AIAN", 
                                            "Best"))) |>
  ggplot(aes(x = year, y = exp(estimate), color = counterfactual))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = counterfactual),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = c("red", "gold", "navy", "darkgreen"))+
  scale_fill_manual(values = c("red", "gold", "navy", "darkgreen"))+
  theme_bw()
```

# Subrace Analysis

```{r}
#| label: fig-sub-hispanic
#| fig-cap: Exogamy of Hispanic subgroups with White and Black partners. White/Black exogamy shown for reference
#| layout-ncol: 2
#| fig-subcap:
#|   - White partner
#|   - Black partner

lims <- exp(c(min(model_hispanic_sub_state_bs$conf.low), 
              max(model_hispanic_sub_state_bs$conf.high)))

model_hispanic_sub_state_bs |>
  filter(str_detect(term, "^White/")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10(limits = lims)+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()

model_hispanic_sub_state_bs |>
  filter(str_detect(term, "^Black/") | term == "White/Black") |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10(limits = lims)+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()
```

```{r}
#| label: fig-pan-hispanic
#| fig-cap: Exogamy of Hispanic subgroups with each other

model_hispanic_sub_state_bs |>
  filter(!str_detect(term, "^Black/|^White/")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10(limits = lims)+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()

```

```{r}
#| label: fig-sub-asian-full
#| fig-cap: Exogamy of Asian subgroups with White partners. 

model_asian_sub_state_bs |>
  filter(str_detect(term, "^White/")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()
```

```{r}
#| label: fig-pan-asian-full
#| fig-cap: Exogamy of Asian subgroups with each other

model_asian_sub_state_bs |>
  filter(!str_detect(term, "^White/")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()

```


```{r}
#| label: fig-sub-asian-simple
#| fig-cap: Exogamy of Asian subgroups with White partners, where East Asian and SE Asian have been combined into East Asian

model_asian_sub_simple_state_bs |>
  filter(str_detect(term, "^White/")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()
```

```{r}
#| label: fig-pan-asian-simple
#| fig-cap: Exogamy of Asian subgroups with each other, where East Asian and SE Asian have been combined into East Asian

model_asian_sub_simple_state_bs |>
  filter(!str_detect(term, "^White/")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()
```

```{r}
#| label: fig-sub-indigenous
#| fig-cap: Exogamy of Indigenous subgroups with White partners.

model_indig_sub_state_bs |>
  filter(str_detect(term, "^White/")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()
```

```{r}
#| label: fig-pan-indigenous
#| fig-cap: Exogamy of Indigenous subgroups with each other

model_indig_sub_state_bs |>
  filter(!str_detect(term, "^White/")) |>
  ggplot(aes(x = year, y = exp(estimate), color = term))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = term),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  scale_y_log10()+
  scale_color_manual(values = palette)+
  scale_fill_manual(values = palette)+
  theme_bw()
```

# Regional Models

```{r}
#| label: fig-region
#| fig-cap: Exogamy of single race groups, separately by region

model_state_byregion_bs |>
  ggplot(aes(x = year, y = exp(estimate), color = region))+
  geom_vline(xintercept = 2000, linetype = 2)+
  geom_ribbon(aes(ymin = exp(conf.low), ymax = exp(conf.high), fill = region),
              alpha = 0.3, color = NA)+
  geom_line()+
  geom_point(size = 0.5)+
  facet_wrap(~term, scales = "free_y")+
  scale_y_log10()+
  scale_color_manual(values = c("red", "gold", "navy", "darkgreen"))+
  scale_fill_manual(values = c("red", "gold", "navy", "darkgreen"))+
  theme_bw()
```

```{r}
#| label: timestamp-end
#| echo: false

timestamp()
```