---
title: "Build Model Data"
params:
  bootstrap_rep: 5
format: html
---

```{r}
#| label: timestamp-start
#| echo: false

timestamp()
```

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

```{r}
#| label: prepare-data
#| include: false

load(here("data", "data_constructed", "individ_data.RData"))

census <- census |>
  # relevel year
  mutate(year = relevel(year, "2000")) |>
  # only native born
  filter(gen_husband == "2nd+" & gen_wife == "2nd+")
```

We will do state and region together. However, there is no need for a bunch of fake zero columns for region which are just going to take up space. So instead, we will just attach region afterwards.

```{r}
#| label: generate-state-region-model-data

tic()
data_model_state <- census |>
  generate_bootstrap_data(params$bootstrap_rep, composition_var = "state")
toc()

# add in the region for each state
region_crosswalk <- census |>
  select(state, region) |>
  distinct()
data_model_state <- data_model_state |>
  map(~ {
    .x |>
      left_join(region_crosswalk, by = "state") |>
      relocate(region, .before = freq)
  })
  
save(data_model_state, 
     file = here("data", "data_constructed", "data_model_state.RData"))
rm(data_model_state)
gc()
```

We have to do a separate best race model data because this variable changes at the individual level.

```{r}
#| label: generate-best-race-model-data

transform_race <- function(race, best_race) {
  
  race <- as.character(race)
  race <- case_when(
    race %in% c("EastAsian", "SEAsian", "SouthAsian", "OtherAsian", 
                "PI") ~ "API",
    TRUE ~ race
  )
  
  race <- if_else(!is.na(best_race), best_race, race)
  race <- factor(race, levels = c("White", "Black", "AIAN", "API"))
  return(race)
}

data_model_best_race_state <- census |>
  mutate(race_husband = transform_race(race_husband, race_best_husband),
         race_wife = transform_race(race_wife, race_best_wife)) |>
  filter(!is.na(race_husband) & !is.na(race_wife)) |>
  generate_bootstrap_data(params$bootstrap_rep, composition_var = "state")

save(data_model_best_race_state, 
     file = here("data", "data_constructed", "data_model_best_race_state.RData"))
```

```{r}
#| label: timestamp-end
#| echo: false

timestamp()
```




